# (C) Copyright 2025, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Astarte Device SDK C++"
SPDX-PackageDownloadLocation = "https://github.com/secomind/astarte-device-sdk-cpp"

[[annotations]]
path = "samples/simple/interfaces/*.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "end_to_end/interfaces/*.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "SECO Mind Srl"
SPDX-License-Identifier = "Apache-2.0"
