# (C) Copyright 2025, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: REUSE Compliance Check

on: [push, pull_request, create]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5
